Feature/add module main
DenisYuminov/MealHelper pull request #29
Opened 2023-05-04 08:56 UTC by DenisYuminov

добавил модуль main, с экранами main, likes, yourRecipes, createRecipe, Recipe

2023-05-08 18:55 UTC, ruslangazizov commented
На экране восстановления пароля не хватает скрола для случая с показанной клавиатурой
![Simulator Screen Shot - iPhone 14 Pro](https://user-images.githubusercontent.com/86663214/236907920-a5d31c2e-150d-4c84-bf99-88115bc1834b.png)

2023-05-08 18:55 UTC, ruslangazizov commented
на экране Auth при нажатии на кнопку "Войти без авторизации" ничего не происходит

2023-05-08 19:06 UTC, ruslangazizov commented
На экране настроек при скроле строчки залазят на картинку, появляется навигейшн бар, картинка не двигается
<img width="420" alt="image" src="https://user-images.githubusercontent.com/86663214/236910377-e806a267-4327-4e12-9c8e-21cc5956105e.png">

2023-05-08 21:29 UTC, ruslangazizov requested changes

2023-05-08 21:29 UTC, ruslangazizov commented on MealHelper/Modules/Main/Main/Main/View/MainViewIO.swift
> +    func getData() -> [Category]
не нашел где используется

2023-05-08 21:29 UTC, ruslangazizov commented on MealHelper/Modules/Main/Main/Main/View/RecipeCollectionViewCell.swift
> +class RecipeCollectionViewCell: UICollectionViewCell {
```suggestion
}

final class RecipeCollectionViewCell: UICollectionViewCell {
```

2023-05-08 21:29 UTC, ruslangazizov commented on MealHelper/Modules/Main/Main/Main/View/RecipeCollectionViewCell.swift
> +        label.font = UIFont.systemFont(ofSize: .ratingLabelFont)
по два раза задается `font`

2023-05-08 21:29 UTC, ruslangazizov commented on MealHelper/Modules/Main/Main/Main/View/RecipeCollectionViewCell.swift
> +    //
rip комменту

2023-05-08 21:29 UTC, ruslangazizov commented on MealHelper/Modules/Main/Main/Main/View/RecipeCollectionViewCell.swift
> +        outerStackView.spacing = .outerStackViewSpacing
можно вынести в проперти

2023-05-08 21:29 UTC, ruslangazizov commented on MealHelper/Modules/Main/Main/Recipe/View/RecipeViewController.swift
> +class RecipeViewController: UIViewController {
```suggestion
final class RecipeViewController: UIViewController {
```

2023-05-08 21:29 UTC, ruslangazizov commented on MealHelper/Modules/Main/Main/Recipe/View/RecipeViewController.swift
> +    private let recipe: RecipeModel
лучше в презентер унести

2023-05-08 21:29 UTC, ruslangazizov commented on MealHelper/Modules/Main/Main/Recipe/View/RecipeViewController.swift
> +        label.text = "Prepare: \(recipe.timeToCook)"
локализация

2023-05-08 21:29 UTC, ruslangazizov commented on MealHelper/Modules/Main/Main/Recipe/View/RecipeViewController.swift
> +            make.bottom.equalToSuperview().inset(80)
а зачем сверху и снизу отступы?

2023-05-08 21:29 UTC, ruslangazizov commented on MealHelper/Modules/Main/Main/Recipe/View/RecipeViewController.swift
> +        }
Зачем задавать ширину и высоту лейблов? Они же сами знают свою и ширину, и высоту (на основе шрифта и текста).

2023-05-08 21:29 UTC, ruslangazizov commented on MealHelper/Modules/Main/Settings/View/SettingsViewController.swift
> +    }()
Зачем? На этом экране нет ничего, что можно было бы переиспользовать. Можно не запариваться с таблицей, думаю обычного стека вполне хватит.

2023-05-08 21:29 UTC, ruslangazizov commented on MealHelper/Modules/Main/Settings/View/SettingsViewController.swift
> +        }
именно поэтому предлагаю стек)

2023-05-08 21:29 UTC, ruslangazizov commented on MealHelper/Modules/Main/TabBar/Coordinator/TabBarCoordinator.swift
> +    weak var tabBarController: UITabBarController?
private

2023-05-08 21:29 UTC, ruslangazizov commented on MealHelper/Modules/Main/TabBar/TabBarViewController.swift
> +class TabBarViewController: UITabBarController {
не увидел где используется

2023-05-08 21:29 UTC, ruslangazizov commented on MealHelper/Modules/Main/YourRecipes/CreateRecipe/Presenter/CreateRecipePresenter.swift
> +    func showYOurRecipe()
```suggestion
    func showYourRecipe()
```

2023-05-08 21:29 UTC, ruslangazizov commented on MealHelper/Modules/Main/YourRecipes/CreateRecipe/View/CreateRecipeViewController.swift
> +    private var cancelButton: UIBarButtonItem!
а почему сразу не создал экземпляр здесь? И вообще не обязательно хранить в теле класса UIBarButtonItem, можно в нужном месте создать и сразу заиспользовать.

2023-05-08 21:29 UTC, ruslangazizov commented on MealHelper/Modules/Main/YourRecipes/CreateRecipe/View/CreateRecipeViewController.swift
> +    // UI
блок UI - огромный, напрашивается на создание кастомных верхнеуровневых вьюшек, которые бы инкапсулировали в себя конкретные низкоуровневые лейблы, текст филды и т.д.

2023-05-08 21:29 UTC, ruslangazizov commented on MealHelper/AppServicesAssembly.swift
> +    var createRecipeSerivce: ICreateRecipeService { get }
```suggestion
    var createRecipeService: ICreateRecipeService { get }
```

2023-05-08 21:29 UTC, ruslangazizov commented on MealHelper/AppPresentationAssembly.swift
> +    var mainMuduleBuilder: IMainModuleBuilder { get }
```suggestion
    var mainModuleBuilder: IMainModuleBuilder { get }
```

2023-05-16 11:46 UTC, ruslangazizov commented on MealHelper/Components/TextView/CommonGrayTextView.swift
> +extension UITextView: UITextViewDelegate {
В итоге методы `addPlaceholder` и `textViewDidChange` теперь больше нигде не используются. Тогда их стоит либо удалить, либо заиспользовать.

2023-05-21 12:36 UTC, ruslangazizov commented on MealHelper/Modules/Main/Main/Main/View/MainViewController.swift
> +        collectionView.layoutIfNeeded()
без этого не работает?

2023-05-21 13:39 UTC, DenisYuminov commented on MealHelper/Modules/Main/Main/Main/View/CollectionHeaderView.swift
> +        label.text = "header"
удалил строчку, заголовок у секции задается из enum при заполнении в MainViewController, там есть локализация

2023-05-21 13:41 UTC, ruslangazizov approved these changes

2023-05-21 13:41 UTC, merged